### ISSUE TITLE
Support expanding of persistent volumes

### ISSUE THREAD

**Issue by adoerler** [LINBIT/drbd-flex-provision#3]
Hi,

thanks for this nice plugins (drbd-flex-provision and drbd-flexvolume). Works pretty good on Kubernetes 1.9.
Do you plan adding support for expanding persistent volumes?

Since Kubernetes 1.8 one can enable expanding volumes by adding the feature-gate `ExpandPersistentVolumes=true` to `apiServer`, `controllerManager` and `scheduler`. Additionally one needs to enable the `PersistentVolumeClaimResize` admission control, see:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims

After this is done, one has to create the storageClass for DRBD with `allowVolumeExpansion: true`.

As `drbdmanage` already supports resizing by issuing a command like `sudo drbdmanage resize-volume pvc-5aa836bf-1e07-11e8-96cc-0050569610c9 0 15MiB` it should technically be possible.

Glusterfs handles `ExpandVolumeDevice` like this:
https://github.com/kubernetes-incubator/external-storage/blob/d30fcc2198e4c4b3aa89640406b7dd477fd0538f/gluster/file/cmd/glusterfile-provisioner/glusterfile-provisioner.go#L256

Currently trying to resize a DRBD PVC returns the error `persistentvolumeclaims "test" is forbidden: volume plugin does not support resize`.

Kind regards from Ländle to Vienna
Andreas

**Comment by haySwim** [comment]
I believe that "volume plugin" here refers to flexvolume itself, and not any specific implementation of a flexvolume driver .

**Comment by adoerler** [comment]
Hi haySwim,

when using glusterfs instead DRBD expanding volumes works, so in my opinion it's not a general problem of flexvolume. Or am I missing something here?

**Comment by haySwim** [comment]
Sure, flexvolume itself does not support resize. Here are the things it allows people to implement:
	
-       attach
- 	detach
- 	waitforattach
- 	isattached
- 	mountdevice
- 	unmountdevice

Flexvolume is a temporary solution to out-of-tree volume provisioning in k8s, so a bunch of the fancier stuff it's never going to do. CSI is the long-term way this is going to be handled, but that's still not quite ready as of right now.
