### ISSUE TITLE
How to use multiple storage classes for different types of hard drives?

### ISSUE THREAD

**Issue by adoerler** [LINBIT/drbd-flex-provision#5]
Hi,

we've a setup of two storage servers containing both SSDs and HDDs.
Therefore it would be great to have two different volume groups and handle them by separate storage classes like `drbdpool-ssd` and `drbdpool-hdd` or `-slow` and `-fast` or whatever.

Currently the only way of handling such a case seems to be creating a `drbdpool` volumegroup over all PVCs (ssd and hdd) and than do a `pvmove` to move the LV onto the corresponding PV.
(see discussion at Proxmox: https://forum.proxmox.com/threads/drbd9-how-to-configure-multiple-volumes.26010/#post-132180)

As `drbdmanage` itself doesn't seem to provide this functionality out of the box (i.e. I couldn't find a way to define multiple pools using the very same LVM plugin), I'm wondering if this provisioner could do the job by issuing pvmove after `add-volume` has been executed.

What do you think?

Kind regards
Andreas

**Comment by haySwim** [comment]
This is not possible with DRBD Manage. Linstor, the successor to DRBD Manage does. Please see linstor-server, linstor-client, linstor-flexvolume, linstor-external provisioner on this repo for details.

**Comment by adoerler** [comment]
Hi haySwim,

thanks for the pointer to linstor. I give it a try and will ping back in the linstor-external-provisioner if I get stuck.
