### ISSUE TITLE
Recommended way of running drbd-flex-provision with enable-controller-attach-detach=true/false

### ISSUE THREAD

**Issue by adoerler** [LINBIT/drbd-flex-provision#6]
Hi,

I've the following setup:

![image](https://user-images.githubusercontent.com/376589/37279575-81c10030-25eb-11e8-9920-538e91a7981d.png)

As there is currently no DRBD (neither Kernel module, nor drbd-utils) and no local storage available on the master I've configured `kubelet` with `--enable-controller-attach-detach=false`. 
`drbd-flex-provision` is running on both nodes and passing the PVCs to `drbdmanage`.

Openshift seems to recommend to run the provisioning from master, i.e.  `--enable-controller-attach-detach=true` as this way the muster can detach volumes and reattach it to another node if one node goes down, see https://docs.openshift.org/latest/install_config/persistent_storage/enabling_controller_attach_detach.html
(Couldn't find the corresponding k8s documentation on this)

Imho it would make sense to have to provisioning controlled from the master side, but I'm not sure whats needed to run the cluster with  `--enable-controller-attach-detach=true` and no local storage on the master?

Do you think the following steps are okay?
* Install DRBD kernel module on master (as it needs to have the DRBD control volume too)
* Install DRBD utils to have access to `drbdmanage`
* Deploy `drbd-flex-provision` to master only (i.e. do not start it on the k8s nodes)
* Issue `drbdmanage add-node --no-storage master <Master-IP>` on one of the nodes after `drbdmanage init` has been completed and all nodes are joined

Many thanks in advance
Andreas

**Comment by haySwim** [comment]
This isn't possible due to issues with netlink namespacing issues (iirc) and DRBD Manage can't run separately from the drbd kernel module. Running with  `--enable-controller-attach-detach=true` might be possible in with the Linstor flexvolume, but it hasn't been a priority yet.

**Comment by adoerler** [comment]
thanks for your explanation.
