### ISSUE TITLE
Could not create PVC successfully 

### ISSUE THREAD

**Issue by selvakumarnms** [LINBIT/drbd-flex-provision#7]
HI ,
I am getting below error during deployment of pvc.
could you provide more steps  on how to add volume 
waiting for a volume to be created, either by external provisioner "external/drbd" or manually created by system administrator

**Comment by haySwim** [comment]
Hi, this is for an older version of our SDS solution, DRBD Manage. You should be using the newer version for LINSTOR: linstor-flex-provisioner

But for both, you'd either have a pre-created resource and use that name. Or name a pvc that uses the external provisoner after having set that up.
